### ISSUE TITLE
Deciding and implementing an image serving system

### ISSUE THREAD

**Issue by RobotsBuildingEducation** [RobotsBuildingEducation/RobotsBuildingEducation#8]
Right now I'm serving long videos via Cloudinary on a free tier. I did not think about it, it's just what I've done for a long time.

The largest video I can upload are 100MB, so sometimes I have to run the video through a video compressor to reduce the size so that I can store it to Cloudinary.

This approach will likely reach a limit in the near future, as in, if I don't think about it, I will just have to pay $99/mo. Given that this is a growing cost, an analysis for the best approach is warranted.

Here is some basic guidance:
Understand

- Cloudinary
- Cloudflare
- Other CDNs like Fastly
- Alternative services
- Creative solutions like github (what would be the limit of this link's usage below? Turns out it's 10MB only)

<img width="376" alt="image" src="https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/1d95d0d8-6a03-44ae-a065-07ae93aaa49b">

🤔 

Discord Nitro 
<img width="308" alt="image" src="https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/fbc98a0d-7058-44b5-81e3-ef9f0deed991">

**Comment by nfa1** [comment]
### **Summary:**

•	Cloudflare is the most affordable content delivery network (CDN) that offers the best image and video quality.
•	It has comprehensive geographic coverage.
•	Cloudinary is a close second, but its lowest-price paid tier is more expensive than Cloudflare’s.
•	Fastly and Amazon CloudFront are both more expensive than Cloudinary, but they offer slightly better image and video quality.
•	Discord Nitro is the least expensive CDN, but it is not recommended because it does not offer the same level of image and video quality as the other CDNs.

### **Analysis:**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Fabian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Fabian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#29A7BE" vlink="#7E5FAE">



CDN | Price/Month | Monthly Max Image File Upload   Size | Monthly Max Video File Upload   Size | Recommendation
-- | -- | -- | -- | --
Cloudflare | $20   annual / $25 monthly | 100   MB | 100   MB | Best   Recommendation
Cloudinary | $89   annual / $99 monthly | 20   MB | 2   GB | Recommended
Fastly | Starts   at $50/month | Unlimited | Unlimited | Recommended
Amazon CloudFront | Starts   at $0.005/GB | Unlimited | Unlimited | Recommended
Discord Nitro | $9.99 | 100   MB | 100   MB | Not   Recommended. Uses Cloudflare as its CDN.



</body>

</html>


As you can see, Cloudflare is the most affordable CDN that offers excellent image and video quality. It also has comprehensive geographic coverage. Cloudinary is a close second, but it is more expensive than Cloudflare. Fastly and Amazon CloudFront are both more expensive than Cloudinary, but they offer slightly better image and video quality. 

Discord Nitro is the least expensive CDN, but it does not offer the same level of image and video quality as the other CDNs. Please note that Discord Nitro uses Cloudflare as its CDN. Since using Discord essentially adds another point of failure, it is not recommended as a CDN.  

Overall, Cloudflare is the best CDN for a tech startup that is looking for the best image and video quality at a reasonable price of $20 monthly ($240 annual payment) or $25 monthly. It has comprehensive geographic coverage, and it offers a variety of features that are tailored to the needs of tech startups.

### **Pricing** Information:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Fabian/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Fabian/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#29A7BE" vlink="#7E5FAE">



CDN | Contact/Pricing Details
-- | --
Cloudflare | https://www.cloudflare.com/plans/application-services/
Cloudinary | https://cloudinary.com/pricing
Fastly | https://rb.gy/0ya65
Amazon CloudFront | https://calculator.aws/#/addService/CloudFront
Discord Nitro | https://discord.com/nitro



</body>

</html>

### **Thoughts/Feedback:**

I hope this analysis is helpful and welcome everyone’s thoughts and feedback. Thanks!

**Comment by RobotsBuildingEducation** [comment]
This is wonderful, thank you.  Yeah I think cloudflare tends to position themselves as a value product. 

They are. I use them for the DNS. This market has always been fascinating to me. I know that fastly specializes in collaborative software and media, so they do a lot of processing on Firebase, GitHub, Reddit, Pinterest, spotify, that sort of thing. 


Cloudinary, I kind of get why they're expensive. They're not really developer first, but they do have some coding stuff. So it's supposed to be more of a packaged service, which for me might actually end up being best. They allow the ability to program videos too, but I wonder if I can just write that myself. 

Tough choice

**Comment by RobotsBuildingEducation** [comment]
so admitting I don't understand. I feel like this should make video calls fail. But they're not (maybe a cache thing). Im waiting for someone to possibly report it, but if not then I guess I can't complain. Either way, I ended up removing the link away from Tiktok and adding a Patreon one instead.

The browser on tiktok was pretty bad and I was pretty much asking for trouble if a video went viral the right way 

<img width="565" alt="image" src="https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/8b64a7f1-021c-4f0f-97db-890d9dc64432">
