### ISSUE TITLE
UI/UX considerations

### ISSUE THREAD

**Issue by RobotsBuildingEducation** [RobotsBuildingEducation/RobotsBuildingEducation#9]
These are the resume items you'll gain:

    • Initiate design system with Figma using smart color palettes
    • Initiate component mapping and design language

---

Right now im essentially using a Japanese color palette from many years ago without much rhyme or reason.
Here is an example: https://codepen.io/EduProjectsIL/pen/gzQexj

I have no standardized approach, layout, and mostly lean on using apple's and react-bootstraps design system to try to shape things.

I would like to create a more reasonable system, likely laid out on Figma, which is a tool many UI/UX experts use.'t 

I don't have a strong opinion on what the design can be. I suppose there is a greater conversation here about having a general design language. Here are some general vibes I can kinda help with:

- Something retro-future toned is cool, eg: https://developer.tbd.website/projects/tbdex/
<img width="969" alt="image" src="https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/610a1e5f-a95c-4ce2-bf62-4a470aacd528">

- Something Japanese toned is pleasant: eg 
![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/d5be42f9-72cd-4881-876d-08276dd749dd)

- Something classically Mexican is tone that I believe creates more safety: eg
![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/fc42bdff-483d-46f4-ae68-e67001fcea94)

![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/0f34f824-c886-4692-abff-e145a325e58b)

**Comment by nfa1** [comment]
I agree that Figma is an effective tool for creating a more cohesive and thoughtful design for RO.B.E. Here's how you can use Figma along with other resources to achieve your goals:

1. Start by gathering inspiration for a new color palette. Since you mentioned using a Japanese color palette, I was able to create a new look for the site using the sample image. I found [Colormind.io](https://colormind.io) a free and easy way to extract colors from the sample picture.
2.  Once you have a new color palette in mind, you can begin implementing it in Figma. Figma allows you to create and manage design components, which can be handy for maintaining consistency across your website. You can define colors as global styles in Figma and reuse them throughout your designs, making it easier to update them later if needed.
3. To transfer your design from Figma to HTML and CSS code, you can leverage free plugins like "fit.to.html" This plugin helps you export your Figma design into code snippets, saving you time and effort in manually translating your designs to frontend code. You can search for and install/run the plugin within Figma's plugin library.

![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/34761234/a522ea86-89b6-4ea1-b8de-41879e6ca936)

By following this process, you'll be able to begin establishing a more systematic approach to your RO.B.E's design. I also will send you a link via Discord DM so you can explore the design in Figma online or through Figma Desktop.

Below is a screenshot using the Japanese color palette:

![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/34761234/b3835eb9-07ae-469d-ae05-3b13d5fd6ae0)

Here are screenshots of the colors used and their Hex color codes:

![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/34761234/51d3d1b7-2da7-4372-bfd1-15714b5b865f)

![image](https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/34761234/c6f6cf46-a9a7-4a58-af8d-6d85aa02d133)


I used this excellent beginner-friendly Figma web design guide to get started.

[Figma for Web Design - A Beginner's Guide | Engineering Education (EngEd) Program | Section](https://www.section.io/engineering-education/using-figma-for-web-design/) 

Figma also offers free lessons to learn how to build custom design systems from scratch.

[Figmaster | Design systems workbook for Figma](https://www.figmaster.co/)

I hope this is helpful as a starting point for exploring RO.B.E's future design changes.

**Comment by neesssam** [comment]
Im interested in helping out! Here's my resume: https://www.canva.com/design/DAFHdyTAQAA/AT0FRIiK_dLAA3QtUqPJkw/edit?utm_content=DAFHdyTAQAA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Please email me more details about the project so I can properly assist: neesssam@gmail.com

**Comment by RobotsBuildingEducation** [comment]
@nfa1 i've updated the Creator section in the app to have a deeper focus in UI/UX and it's related domains. One part that I have included is how psychology applications are approaching design and experience.

https://howwefeel.org/

check this out on your phone and let me know what you think if you ever have time to explore that. I found it pretty interesting. I don't want to suggest what it is to prime your thoughts because it may be different for you.

**Comment by RobotsBuildingEducation** [comment]
I asked chatGPT and it gave me this lol

```
export let japaneseThemePalette = {
  CherryBlossomPink: "#FFB7C5",
  KyotoPurple: "#663399",
  FujiSanBlue: "#3A5F7D",
  TokyoTwilight: "#706fd3",
  SakuraMochiPink: "#FF92A9",
  WisteriaPurple: "#89729E",
};

```

**Comment by RobotsBuildingEducation** [comment]
not a bad run
<img width="738" alt="image" src="https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/assets/65219666/7cf56865-eca7-4252-b3b2-4f7c2feac8cf">

**Comment by nfa1** [comment]
> @nfa1 i've updated the Creator section in the app to have a deeper focus in UI/UX and it's related domains. One part that I have included is how psychology applications are approaching design and experience.
> 
> https://howwefeel.org/
> 
> check this out on your phone and let me know what you think if you ever have time to explore that. I found it pretty interesting. I don't want to suggest what it is to prime your thoughts because it may be different for you.

My first overall impression of its UI as a therapeutic version of TikTok. Their choice of dark mode as the default is excellent which encouraged me to continue exploring the app. 

The onboarding process was easy and intuitive. I especially liked the ability to select my current feelings, location, social environment, and activity using both predefined and custom values. For instance, I was asked what I was currently doing and I entered "programming and learning AI." I am not exactly sure how the app will use this type of data but my best guess is it will be used to recommend future relevant lessons and exercises.

The app's color palette is warm and relaxing which made me feel calm and at ease using it. I like how the app can recommend lessons as you start using it while also granting you access to view lessons on your own. 

The video lessons are well-produced with instructors who made me like I was in a private, guided therapy session. The length of the videos ranges between 1 to 3 minutes to accommodate shorter attention spans while still providing value through a self-contained lesson or exercise. 

Overall, I feel that the UX app is relevant and optimized for its users who are seeking short lessons and exercises to track, monitor and self-regulate their emotions. I now understand why you found it interesting. Since it is essentially self-therapy in your pocket, its UI and design decisions inspire new features in future versions of Robots Building Education.

**Comment by RobotsBuildingEducation** [comment]
@nfa1 gonna extend this a little and start laying out some ground work for toggling interesting themes: https://github.com/RobotsBuildingEducation/RobotsBuildingEducation/issues/33

changing this issue to be a general UI/UX thing but themes should see some light once the code is refactored more and more over time
